### ISSUE TITLE
Question about default page model and routing

### ISSUE THREAD

**Issue by NickDarvey** [OnurGumus/FBlazorShop#1]
I have a question about this change:

https://github.com/OnurGumus/FBlazorShop/commit/d7e793c78393aa65ce42eec04fdc30e4b5e42e0c#diff-a07b110b44272e9eb6487d1e0fdc3c41R52

I have a similar routing for one of my pages where there's expected to be a route parameter. Right now my issue is that parameter is null. I've traced it back to here, my `defaultPageModel`. I see here you're doing a null check on key. In what cases should I expect it to be null? In what cases would it actually be the value I'm expecting?

(In my case I'm performing a navigation (via a router.Link) and I can see the route parameter does exist in the href, however the page model is created here with a null.)

**Comment by OnurGumus** [comment]
Hi, it has been too much time passed, but IIRC, when bolero starts in order to resolve those attributes on the Page discriminated union, it attempts to construct each union case via reflection with null values. So that's when your model is initialized with complete null values. I find bolero's router quiet hacky, I think they attempted to backport from WebSharper, better ask to @Tarmil why it works this way.

**Comment by NickDarvey** [comment]
Ahh, interesting. Have you tried using your own router before instead?

**Comment by OnurGumus** [comment]
No, I am actually developing a Fable.Elmish app for work. I kinda have mixed feelings about the model binding of Bolero. In Fable you just don't get that at all. On the overall, it requires a bit rework from Bolero side, most significantly, Model binding doesn't support custom routers and you really need to get how it works, and it is still quite confusing to me.
